name: Deploy to Azure App Service
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # Match Azure App Service Python version
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create startup command file
        run: |
          echo "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000" > startup.sh
          chmod +x startup.sh
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: HrAI
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          startup-command: "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
          
      - name: Log deployment details
        run: |
          echo "Deployment to HrAI completed at $(date)" >> deployment.log
          git log -1 >> deployment.log