name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Create and activate virtual environment
      run: |
        python -m venv antenv
        source antenv/bin/activate

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install uvicorn fastapi
        pip install --no-cache-dir -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: HrAI
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

    - name: Log deployment details
      run: |
        echo "Deployment to HrAI completed at $(date)" >> deployment.log
        git log -1 >> deployment.log
