name: Deploy to Azure App Service
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create startup script
        run: |
          echo '#!/bin/bash' > startup.sh
          echo 'cd /home/site/wwwroot/' >> startup.sh
          echo 'pip install -r requirements.txt' >> startup.sh
          echo 'python -m uvicorn app.main:app --host 0.0.0.0 --port 8000' >> startup.sh
          chmod +x startup.sh
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: HrAI
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}